### ISSUE TITLE
Filepath Case Sensitivity

### ISSUE THREAD

**Issue by Nightro** [SimpsonGSD/P4EditVS#12]
I've noticed in my Unreal Engine project that randomly, Visual Studio for *some* reason loses the case accuracy of the file path. I can see this even by right clicking on a file and selecting "Copy Full Path". Unfortunately, it looks like P4 command line is case sensitive for file paths. That means that sometimes, P4EditVS works fine... but at some point this breaks and it gives the error "file(s) not on client." when I try to perform any p4 operations and will continue this trend until I re-open the solution.

Is there possibly a way you could fix this by grabbing the correct casing for a given filepath from the disk?

Here's a fake example (my project is NDA).

Right:
D:\Something\v4.0\Project\Plugins\Private\StackCameraUtils.cpp

Wrong:
d:\something\v4.0\project\Plugins\Private\StackCameraUtils.cpp

Thanks
Ant

**Comment by SimpsonGSD** [comment]
Hi Ant
In what version of Visual Studio does this happen?

**Comment by Nightro** [comment]
VS 2019, but I haven't gotten this for a few days now. It's possible I
needed to reboot after installing, but I'm worried it's just sporadic.

**Comment by SimpsonGSD** [comment]
I have seen Visual Studio 2019 do this but I don't run a case-sensitive P4 server so I haven't seen this issue. 
I'll add a fix.

**Comment by SimpsonGSD** [comment]
@Nightro I've released v2.6 to try and fix this issue. Let me know if it improves the situation.
Thanks.

**Comment by Nightro** [comment]
Excellent, thank you!

**Comment by Nightro** [comment]
So far so good! I haven't run into the issue again since your fix. Thank you very much :)

**Comment by SimpsonGSD** [comment]
Great, thanks for reporting back. I'll close this for now. If you do still have issues then just let me know.
Thanks.

**Comment by Colourclash** [comment]
Hi, I am also experiencing this case sensitivity issue. I am on P4EditVS v2.63. I am using Visual Studio 2019 v16.11.9

I am experiencing the exact same symptoms as the OP. When I open a source file VS will, for some reason, open it with part of the path converted to lower case, eg D:\Root\CryEngine\Tools\App.xaml will become  d:\root\cryengine\Tools\App.xaml. When I try to check the file out it will fail with `stderr: d:\root\cryengine\App.xaml - file(s) not on client.`

I understand this seems to be a Visual Studio problem so not expecting a fix but I thought you might want to know. :)

**Comment by SimpsonGSD** [comment]
So as far as I know `d:\root\cryengine\App.xaml` should be the correct casing.
If you do `p4 edit d:\root\cryengine\App.xaml` in command prompt does it also fail? And if so, does it work if you do `p4 edit D:\Root\CryEngine\Tools\App.xaml` ?

Are you definitely running a case sensitive Perforce sever?

**Comment by Colourclash** [comment]
I'm definitely running a case sensitive server. When I do `p4 info` it says `Case Handling: sensitive`

> So as far as I know d:\root\cryengine\App.xaml should be the correct casing.

No, the correct casing is `D:\Root\CryEngine\Tools\App.xaml`. If I open a command prompt and do `p4 edit -c default "D:\Root\CryEngine\Tools\App.xaml"` it checks out the file fine. However `p4 edit -c default "d:\root\cryEngine\Tools\App.xaml"` fails with `file(s) not on client`. I have obfuscated the actual path because of confidentiality.

**Comment by SimpsonGSD** [comment]
Ok thanks. 
I do try to query the correct file path from Windows but this obviously still not correct. 
I will continue to look into this.

**Comment by SimpsonGSD** [comment]
Hi @Colourclash is there any chance you could try a build of 2.6.4 to see if it fixes your issue?
You can download it here:
https://dev.azure.com/simpsongsd/d05507bf-aff7-4d89-8ead-6c4562f2df18/_apis/build/builds/98/artifacts?artifactName=P4EditVS&api-version=7.0&%24format=zip

**Comment by Colourclash** [comment]
I downloaded v2.6.4 and it works now. I have tried a few files that VS has messed up the case of the path and they all CheckOut fine with P4EditVS.

Thank you so much. You are awesome. :) 🥇

**Comment by SimpsonGSD** [comment]
Excellent, glad to hear that. Thanks for testing.

I will continue some testing and push that version live soon.

**Comment by SimpsonGSD** [comment]
2.6.4 has been pushed live.
