### ISSUE TITLE
Support for Visual Studio 2022

### ISSUE THREAD

**Issue by 1of4** [SimpsonGSD/P4EditVS#14]
Please enable the support for VS 2022. The VS Beta is working pretty well, I miss a good Perforce extension :=)

Best regards
Alex

**Comment by 1of4** [comment]
Hi, thank you very much.

I have already tried it by myself but I'm not really into the VS Extension world so my attempt wasn't successful.
I could install 'my' test version but it won't load :( because of an error.

Best regards
Alex

**Comment by 1of4** [comment]
Hi,
Any updates?

**Comment by SimpsonGSD** [comment]
Sorry not at the moment - I've not had time. It is the current thing on my list though - so hopefully soon.

**Comment by 1of4** [comment]
Thank you!

**Comment by 1of4** [comment]
That's so great!
I first quick test didn't show any issues.
Installation and checkin' out files are working :)
Thank you
Alex

**Comment by SimpsonGSD** [comment]
That's good to hear!

**Comment by 1of4** [comment]
Hi,
I had no problems so far.
Everything works smooth - thank you!

**Comment by EugeneFominPlaywing** [comment]
Everything works fine! Thank you, Scott!

**Comment by SimpsonGSD** [comment]
Thanks for the feedback :) 
Once VS marketplace supports multiple VSIXs per extension it will be published to there. In the meantime find it in the Releases section. 
Closing this for now.
