### ISSUE TITLE
Benefits over P4VS?

### ISSUE THREAD

**Issue by joschmo80** [SimpsonGSD/P4EditVS#17]
Can you please list (here or in your project landing page) the benefits of this plugin over https://www.perforce.com/perforce/doc.current/user/p4vsnotes.txt ?  I am a long time user of P4VS, and was bummed to see that P4VS does not support VS2022 yet.

**Comment by SimpsonGSD** [comment]
Hi. This isn't a direct competitor to P4VS. This is a much more lightweight plugin that enables basic Perforce integration within Visual Studio.

Generally, users who have seeked out this plugin as an alternative to P4VS are people who have been unhappy with the performance impact the official plugin can have on Visual Studio.

**Comment by SimpsonGSD** [comment]
I will clarify the differences in the readme.

**Comment by joschmo80** [comment]
OK, thank you - much appreciated!
