### ISSUE TITLE
Time lapse view should specify current line when possible

### ISSUE THREAD

**Issue by tom-seddon** [SimpsonGSD/P4EditVS#20]
When possible - so, definitely at least when invoked from an editor tab - invoke as `p4vc -l LINE FILE`. The `-l` flag opens the time lapse view with the given line highlighted, and also enables line numbers by default.

PR to hopefully follow at some point.

--Tom

**Comment by tom-seddon** [comment]
Is it easy to add stuff to the right click menu?
![image](https://user-images.githubusercontent.com/1269020/152537594-6a34e7c1-1f7c-49b9-9153-14ac944b6780.png)
Looks like the line numbers column isn't clickable, so that's a shame.

Anyway, maybe this could be at least a partial solution for #11. Though the `-l` option only works for the first invocation for a given file. (p4vc will re-use the window for subsequent invocations, but the `-l` option doesn't work.) So not much fun if you want quick history for a bunch of lines.

--Tom

**Comment by SimpsonGSD** [comment]
Oh great, the original aim was to do this but I didn't know the commandline and got side tracked.

**Comment by SimpsonGSD** [comment]
> Is it easy to add stuff to the right click menu? ![image](https://user-images.githubusercontent.com/1269020/152537594-6a34e7c1-1f7c-49b9-9153-14ac944b6780.png) Looks like the line numbers column isn't clickable, so that's a shame.
> 
> Anyway, maybe this could be at least a partial solution for #11. Though the `-l` option only works for the first invocation for a given file. (p4vc will re-use the window for subsequent invocations, but the `-l` option doesn't work.) So not much fun if you want quick history for a bunch of lines.
> 
> --Tom

It should be easy enough to add a right-click if you can find the correct ID, it will most likely start with `IDM_VS_CTXT_`. You can then add it to the command table (.vsct).

For #11 I was going to use [ `p4 annotate`](https://www.perforce.com/manuals/cmdref/Content/CmdRef/p4_annotate.html) which gets the revision/user/data/CL/etc for each line of the file. I just don't know the best way to integrate into the IDE that isn't intrusive and has zero performance impact.
