### ISSUE TITLE
Output window switches to P4EditVS when first written to and can be annoying

### ISSUE THREAD

**Issue by SimpsonGSD** [SimpsonGSD/P4EditVS#34]
The output window swaps to P4EditVS's output pane when the solution settings are loaded. 
As the plugin is async loaded it can take quite a while for it to be initialized meaning it can take focus in the middle of doing something such as building.

Try to see if there's a way to not take focus or initialize earlier if possible.

**Comment by Ben136KBC** [comment]
Thank you. Maybe in settings there can be an option to suppress the string "Solution settings C:\Users\xxxxx\AppData\Roaming\P4EditVS\petro-sim_194D2ED7.xml loaded" maybe an option to only show problems?

Thank you for this extension, we love it, and the fact that it is so low impact. The only minor issue is this.

**Comment by SimpsonGSD** [comment]
Version 2.6.7 should fix this and has been pushed to marketplace. VS should auto-install it the next time you reboot. Please let me know if this resolves your issue (and that 2.6.7 is definitely installed).
Thanks.

**Comment by Ben136KBC** [comment]
Thank you kindly, Sir! It seems better now.

**Comment by SimpsonGSD** [comment]
Great. Closing this for now.
