### ISSUE TITLE
Diff uses P4V's diff tool even if a different diff tool is specified in P4V's preferences

### ISSUE THREAD

**Issue by arycama** [SimpsonGSD/P4EditVS#35]
Since this plugin is for visual studio, I wanted my diffs to also appear in visual studio, instead of opening in a seperate program. However, the diffs seem to always open using P4V's diff tool, even if I specify for them to use Visual Studios' diff tool in P4V's preferences.

P4EditVS should either allow configuration to open diffs in Visual Studio, or it should respect whatever is set in P4V preferences.

**Comment by SimpsonGSD** [comment]
Hey, it _should_ use what is set in P4V. It definitely does for me. 
Did you do a PC restart after changing the value?
All P4EditVS does is execute `p4vc diffhave <file>`.

**Comment by arycama** [comment]
Right, looks like a restart was needed to make the changes take affect. Sorry about that!
