### ISSUE TITLE
Open in P4V fails with P4V 2024.1

### ISSUE THREAD

**Issue by fmod-mathew** [SimpsonGSD/P4EditVS#39]
In P4V 2024.1 with "bug fix" [#119251](https://www.perforce.com/perforce/doc.current/user/p4vnotes.txt), they changed the command line for the Open in P4V functionality. Rather than `p4vc -s <file name>` you must now use `p4vc workspacewindow -s <file name>` or you get a popup error message.

One upside of fixing this is you can close #36 as this is the new behavior.

For completeness, here is the note from the P4V revision history:

> #119251 (Change #2555854)
>     'p4v -s', and 'p4v -t' now tells you to run 'p4vc workspacewindow -s', or 'p4vc
>     workspacewindow -t'. The workspacewindow provides the same functionality as
>     running P4V. If you run 'p4vc workspacewindow -s <filename>' and a
>     workspacewindow is already running connected to that client, it brings the
>     application to the foreground and selects that file in either the workspace or
>     depot tree instead of opening a second window.

**Comment by SimpsonGSD** [comment]
thanks for this, will look into it

**Comment by SimpsonGSD** [comment]
Please try v2.6.8 https://github.com/SimpsonGSD/P4EditVS/releases/tag/v2.6.8
I will push it to marketplace soon.

**Comment by fmod-mathew** [comment]
Thanks very much for the speedy turnaround, works great.

**Comment by SimpsonGSD** [comment]
Great, thanks for the update.
