### ISSUE TITLE
[Bug] Handling spaces in file path

### ISSUE THREAD

**Issue by ken-fungi** [SimpsonGSD/P4EditVS#4]
Getting `stderr: file(s) not on client` when checking out/performing any actions on file paths with spaces in folder/file names.
Should work if we surround `filePath` in `Commands` with quotes ""?

P.S. Thank you! Was looking for a lightweight Perforce plugin and found this in the Visual Studio Marketplace! Love it!

**Comment by SimpsonGSD** [comment]
Hi, thank you for your report. I will look at this ASAP.
I'm glad you find this plug-in useful 🙂
