### ISSUE TITLE
Extension can cause save as dialog to appear even though file is checked out

### ISSUE THREAD

**Issue by SimpsonGSD** [SimpsonGSD/P4EditVS#40]
Reported on marketplace:

Using ctrl+s to save can frequently cause the file save as dialog to appear even when the file is checked out.
Disabling the extension does stop this from occurring. 

Environment:
* Windows 11, up-to-date
* Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.1
* P4V Rev. P4V/NTX64/2023.3/2495381
* Project is checked out with default settings (e.g. read-only means not checked out, etc).

**Comment by SimpsonGSD** [comment]
If anyone else sees this issue please upvote this comment. Additionally adding any extra info to the issue would help a lot.

**Comment by SimpsonGSD** [comment]
Closing as issue has been confirmed to not be caused by P4EditVS.

**Comment by cathei** [comment]
Hello, @SimpsonGSD! Thank you for great plugin. I am seeing this issue as well. Did you figure out the cause?

**Comment by SimpsonGSD** [comment]
@cathei the reported issue was not caused by P4EditVS. Can you share more information on what you're seeing and how you're reproducting the issue?

**Comment by cathei** [comment]
Oh nevermind, I found the cause. It was Unreal Integration plugin's doing.
https://forums.unrealengine.com/t/unrealheadertool-running-every-time-i-save-in-visual-studio-2022/1361724

**Comment by SimpsonGSD** [comment]
Interesting, good to know. Thanks for the follow up.
